# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 76019a72489ae14e1d2e8ef38f3e00ca2931cb7699a9320e1978ea75728f3413a3d24780b484f21493155980c67becc0b4f4c09c91a15b3f244dfe0d8e697d25

test:
  secret_key_base: 1d55b2aec6a6e6a0e6a7743cc5a1091911a5dfe21f27a0d0a413d217a52c806a89b7f03b699092801c0956919275ad662d0b3fa8cf5cfe7de2360994adab4322

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
